### ISSUE TITLE
Asteroids disguised as ships?

### ISSUE THREAD

**Issue by DimlyMoonbeam** [Amazinite/Enigma-Corp#16]
I've occasionally seen ships floating around, behaving like asteroids.   I do not recall the exact number of times, but I have seen this more than 3 times for sure.  The ship is not clickable, and is not selected when pressing the target hotkey.

Edit\* I don't _think_ that this happens when your mod is not installed, but I did not exhaustively check that.

**Comment by Amazinite** [comment]
This is from commit 051b5a3. It's something I'm experimenting with and I'm going to expand on later.

These "minable" ships are only found in uninhabited systems and are suppose to be long abandoned ships that pirates did not think were worth looting. I'm currently working on them dropping damaged outfits and ship parts instead of minerals to make it more realistic, and will also add in new sprites for these abandoned ships that look old and damaged as to make them easily distinguishable from normal ships.

**Comment by DimlyMoonbeam** [comment]
Oh OK, very cool.  

Is the normal behaviour here to close the issue now?  That certainly resolved it for me.

**Comment by Amazinite** [comment]
Yup. If an issue is resolved then the issuer (would that be the proper term?) usually closes it. Something I can do too. :)
